import { Certificate } from "@/types/content";

export const certificates: Certificate[] = [
  {
    id: "ace-cpt",
    slug: "ace-certified-personal-trainer",
    title: "ACE Certified Personal Trainer (ACE-CPT)",
    issuer: "American Council on Exercise",
    credentialId: "ACE-CPT-982412",
    year: 2019,
    date: "June 2019",
    expiryDate: "Active / Recertified 2025",
    description: "[PLACEHOLDER] Gold-standard NCCA-accredited certification covering integrated fitness training, behavioral modification, assessment-driven exercise design, and anatomical foundations.",
    verificationUrl: "https://www.acefitness.org/verify-credentials",
    skills: ["Program Design", "Movement Assessment", "Postural Restoration", "Exercise Physiology"],
  },
  {
    id: "nsca-cscs",
    slug: "nsca-certified-strength-conditioning-specialist",
    title: "Certified Strength and Conditioning Specialist (CSCS)",
    issuer: "National Strength and Conditioning Association (NSCA)",
    credentialId: "NSCA-CSCS-710499",
    year: 2021,
    date: "November 2021",
    expiryDate: "Active / Valid through 2027",
    description: "[PLACEHOLDER] Rigorous scientific credential certifying high-level expertise in strength training, speed and agility mechanics, athletic periodization, and bioenergetics.",
    verificationUrl: "https://www.nsca.com/credentials",
    skills: ["Athletic Performance", "Power Development", "Periodization", "Force-Velocity Profiling"],
  },
  {
    id: "pn1-nutrition",
    slug: "precision-nutrition-level-1",
    title: "Precision Nutrition Certified Coach (Pn1)",
    issuer: "Precision Nutrition",
    credentialId: "PN-L1-43209",
    year: 2020,
    date: "August 2020",
    description: "[PLACEHOLDER] Evidence-based dietary coaching credential focusing on nutritional biochemistry, energy balance, psychological habit loops, and practical macronutrient periodization.",
    verificationUrl: "https://www.precisionnutrition.com/verify",
    skills: ["Macronutrient Periodization", "Metabolic Health", "Habit-Based Coaching", "Body Recomposition"],
  },
  {
    id: "cpr-aed",
    slug: "cpr-aed-first-aid",
    title: "CPR / AED / First Aid Certification",
    issuer: "American Heart Association",
    credentialId: "AHA-BLS-88310",
    year: 2024,
    date: "January 2024",
    expiryDate: "January 2026",
    description: "[PLACEHOLDER] Basic Life Support (BLS) certification covering adult CPR, automated external defibrillator operation, and rapid emergency triage response.",
    verificationUrl: "https://cpr.heart.org/verify",
    skills: ["Emergency Response", "Cardiopulmonary Resuscitation", "AED Operation", "Client Safety"],
  },
  {
    id: "frc-mobility",
    slug: "functional-range-conditioning",
    title: "Functional Range Conditioning Mobility Specialist (FRCms)",
    issuer: "Functional Anatomy Seminars",
    credentialId: "FRCMS-10492",
    year: 2022,
    date: "October 2022",
    description: "[PLACEHOLDER] Joint articular mobility certification focusing on controlled articular rotations (CARs), progressive tissue load tolerance, and end-range neurological control.",
    verificationUrl: "https://functionalanatomyseminars.com/verify",
    skills: ["Joint Mobility", "End-Range Strength", "Injury Mitigation", "Active Flexibility"],
  },
];
