import { Plan } from "@/types/content";

export const plans: Plan[] = [
  {
    id: "online-coaching",
    slug: "online-coaching",
    name: "Online Coaching",
    description: "Full remote coaching architecture combining personalized training regimens, precise nutrition periodization, and weekly video analysis.",
    startingPrice: "₹4,999",
    period: "per month",
    suitableFor: "Busy professionals, travelers, and independent trainees who want elite programming and strict accountability.",
    deliveryMethod: "Weekly video check-ins, app-based tracking, asynchronous video form audits.",
    includesNutrition: true,
    features: [
      "Custom 4-8 week training block tailored to equipment access",
      "Macro & micronutrient targets mapped to your metabolic baseline",
      "Weekly video check-in call with progress adjustments",
      "Asynchronous lift form critique via private messaging",
      "Sleep hygiene and stress-management protocols",
      "Direct chat access with guaranteed 24h response",
    ],
  },
  {
    id: "personal-training",
    slug: "personal-training",
    name: "1-on-1 In-Person Training",
    description: "Hands-on, in-gym personal training focused on biomechanical perfection, safe progressive overload, and maximum training intensity.",
    startingPrice: "₹1,499",
    period: "per session",
    recommended: true,
    suitableFor: "Local clients in Mumbai/Bengaluru seeking high-touch coaching, tactile form cues, and guaranteed training intensity.",
    deliveryMethod: "Private gym facility / partnered training studios.",
    includesNutrition: true,
    features: [
      "60-minute intensive guided training sessions",
      "Immediate tactile and verbal form correction",
      "Mobility screening and tailored dynamic warm-up protocol",
      "Full digital workout log and progression tracking",
      "Complimentary nutritional roadmap & calorie planning",
      "Monthly body composition and caliper tracking",
    ],
  },
  {
    id: "custom-consultation",
    slug: "custom-consultation",
    name: "Strategy & Form Audit",
    description: "An intensive single-session diagnostic deep dive to break through stubborn strength plateaus, address aches, and audit your training split.",
    startingPrice: "₹2,499",
    period: "one-time",
    suitableFor: "Intermediate or advanced trainees who already train consistently but have hit a plateau or persistent technique barrier.",
    deliveryMethod: "90-minute live video conference + detailed written roadmap.",
    includesNutrition: false,
    features: [
      "90-minute 1-on-1 comprehensive strategy consultation",
      "Frame-by-frame analysis of your top 3 compound lifts",
      "Complete audit of current training volume and fatigue",
      "Tailored 6-week corrective progression blueprint",
      "Two weeks of follow-up email Q&A support",
    ],
  },
  {
    id: "yearly-transformation",
    slug: "yearly-transformation",
    name: "Yearly Transformation Retainer",
    description: "Long-term partnership designed for complete physical recomposition, habit integration, and year-round peak physical vitality.",
    startingPrice: "₹44,999",
    period: "per year",
    suitableFor: "Individuals committed to profound, sustainable lifestyle transformation without seasonal relapse.",
    deliveryMethod: "Hybrid: ongoing online coaching with priority direct communication.",
    includesNutrition: true,
    features: [
      "Year-round phased periodization (Hypertrophy, Strength, Deload, Peak)",
      "Continuous nutritional adaptations matching metabolic shifts",
      "Priority direct messaging and async review with Siddharth",
      "Bi-weekly detailed performance reviews",
      "Travel and holiday workout adjustment protocols",
      "Quarterly fitness benchmarking and movement assessments",
    ],
  },
];
